<?php
/**
 * Дебаг 
 */
namespace tsframe;

use tsframe\App;
use tsframe\Config;
use tsframe\module\Debugger;

if(App::isDev()){
	$debug = new Debugger;

	Hook::register('http.send', function(&$body, &$headers, $code, $type) use ($debug){
		$data = $debug->getData();
		foreach ($data as $key => $value) {
			$headers['X-Debug-' . $key] = $value;
		}

		if(stripos($type, 'html') !== false){
			$script = "<script>/* generated by debug plugin */";
			foreach ($data as $key => $value) {
				$script .= "console.log('[Its-debug] ' + " . json_encode($key) . " + ': ' + " . json_encode($value) . " );";
			}
			$script .= "</script></body>";

			$body = str_replace('</body>', $script, $body);
		}
	});

	Hook::register('database.query', function($sth) use ($debug){
		$debug->dbQuery(str_replace("\n", '; ', $sth->getDebug()));
	});
}