CREATE TABLE IF NOT EXISTS `tasks` ( 
	`name` VARCHAR(250) NOT NULL , 
	`period` VARCHAR(100) NOT NULL , 
	`last-exec` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	UNIQUE (`name`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;