CREATE TABLE IF NOT EXISTS `log` ( 
	`id` INT NOT NULL AUTO_INCREMENT , 
	`type` VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
	`data` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'JSON' , 
	`date` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	PRIMARY KEY (`id`)
) ENGINE = InnoDB;

ALTER TABLE `log` CHANGE `id` `id` VARCHAR(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `log` CHANGE `date` `date` TIMESTAMP(6) on update CURRENT_TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);