CREATE TABLE `web-push-clients` ( 
	`id` INT NOT NULL AUTO_INCREMENT , 
	`endpoint` VARCHAR(300) NOT NULL , 
	`p256dh` VARCHAR(150) NOT NULL UNIQUE, 
	`auth` VARCHAR(50) NOT NULL UNIQUE, 
	`country` VARCHAR(250) NOT NULL , 
	`city` VARCHAR(250) NOT NULL , 
	`ip` VARCHAR(100) NOT NULL , 
	PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;