CREATE TABLE IF NOT EXISTS `logger` ( 
	`id` VARCHAR(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
	`section` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'default' , 
	`level` INT(1) NOT NULL , 
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	`data` MEDIUMTEXT NOT NULL, 
	PRIMARY KEY (`id`)
) ENGINE = InnoDB; 